added images to the team-section, styled
Endorze/Group-assignment1 pull request #15
Opened 2024-10-16 13:10 UTC by Lvhacker1

2024-10-16 19:40 UTC, Meazajao approved these changes

2024-10-17 09:42 UTC, Endorze requested changes
1 commit behind main in your branch, make sure to be 0 behind and then its good to go.

2024-10-17 14:46 UTC, Lvhacker1 commented
done, 0 behind

2024-10-17 15:35 UTC, Endorze approved these changes
I'm a handsome cat

2024-10-17 15:37 UTC, merged