feat: Started working on footer for homepage
Endorze/Group-assignment1 pull request #16
Opened 2024-10-16 13:19 UTC by Endorze

![image](https://github.com/user-attachments/assets/e1b50500-91cf-4432-a79b-80639502a36e)

2024-10-16 13:34 UTC, Lvhacker1 commented
You’ve accidentally duplicated "contact us" one is enough. 
Maybe remove the dash from Storgatan-12 (just an opinion as it might look better)? 
In your anchor tag you could reconsider removing text-decoration and changing to a more visible color.

2024-10-16 13:46 UTC, Lvhacker1 requested changes
You’ve accidentally duplicated "contact us" one is enough.
Maybe remove the dash from Storgatan-12 (just an opinion as it might look better)?
In your anchor tag you could reconsider removing text-decoration and changing to a more visible color.

2024-10-17 09:48 UTC, Meazajao approved these changes

2024-10-17 14:54 UTC, Lvhacker1 approved these changes
Great job fixing it! The changes looks much better.

2024-10-17 14:54 UTC, merged