Feautre/changes page
Endorze/Group-assignment1 pull request #17
Opened 2024-10-16 13:56 UTC by Maedeh86

Changes Made:
Updated HTML structure for better semantic organization.
Implemented a countdown timer for the "coming soon" page.
Added form validation for the email subscription input.
Enhanced accessibility with appropriate attributes.

2024-10-16 14:28 UTC, Endorze requested changes
It is not okay to copy paste code and consider an assignment done.
The css contains tonnes of classes that you're not using in the html, you're not using the global variables that we've spoken about, the html does not make sense as it seems to be generated and has nothing to do with the assignment.

2024-10-16 17:08 UTC, andre84o approved these changes

2024-10-16 17:08 UTC, andre84o approved these changes

2024-10-16 19:40 UTC, Maedeh86 commented
jag kommer och fixa 
 den var bara så där för att komma in

2024-10-16 22:23 UTC, Maedeh86 commented
Ändringar i projektet:

Lade till en sektion om Git-kommandon: Jag har skapat en ny sektion i HTML där vanliga Git-kommandon som git status, git add, git commit, och git push förklaras med tillhörande beskrivningar. Detta ska hjälpa användare att förstå hur man gör ändringar och följer upp i ett projekt.
Skapade en timer-box: Jag har lagt till en statisk timer precis ovanför foten på sidan. Timern är inramad i en separat box med stil för att markera nedräkningen på sidan.
Justering av layout: Jag har sett till att timern och informationen om Git-kommandon är centralt placerade och tydligt avskilda från varandra. CSS har justerats för att skapa en konsekvent och användarvänlig design utan att ändra färgschemat.
Förbättrad struktur: Jag har omorganiserat HTML-strukturen för bättre semantisk tydlighet och använt CSS för att skapa en tydlig layout med en ren visuell hierarki.
ändrade färger som det ska vara

2024-10-16 22:26 UTC, Maedeh86 commented
Added a Git Commands Section: I’ve created a new section in the HTML that explains common Git commands like git status, git add, git commit, and git push, with descriptions. This helps users understand how to track and apply changes in a project.
Implemented a Timer Box: I added a static countdown timer just above the footer of the page. The timer is enclosed in a separate box for clarity and is styled to make the countdown visible on the page.
Layout Adjustments: The layout has been updated so that the timer and the Git command information are centered and clearly separated. The CSS has been adjusted to ensure a consistent, user-friendly design without altering the color scheme.
Improved Structure: The HTML structure has been reorganized for better semantic clarity, and CSS has been used to create a clean visual hierarchy and layout.

2024-10-17 09:22 UTC, Endorze commented
You have not pushed your changes to the branch, its still the same old reviewed code.

2024-10-17 13:30 UTC, Maedeh86 commented
In our project, we've structured a web page focused on Git commands and their usage. We've created a navigation bar and a main content area that includes explanations of various Git commands, such as git status, git add, git commit, and git push. Additionally, we've implemented a countdown timer for our project launch. Adjustments were made to the layout to ensure that all elements are well-positioned and visible.

2024-10-17 22:13 UTC, Endorze approved these changes
Looks good! 😄

2024-10-17 22:24 UTC, merged